default: &default 
  adapter: mysql2 
  encoding: utf8 
  url: <%= ENV['DATABASE_URL'] %>

development: 
  <<: *default 
  database: applicaster_development

test: 
  <<: *default 
  database: applicaster_test

qa: 
  <<: *default 
  database: applicast_production

production: 
  <<: *default 
  database: applicast_production 
  reconnect: true