# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bbfcec15949140f4be7797408a256c8826a941d6d5a3f56101b9a9408cd581584b986aee2c2d975ef1232f251946117b0cd316f7ab180e80ec48740b9166447

test:
  secret_key_base: 908ef71c951a5024924272bd516df55cb0c4cf1cb72ce3fcee89c2ae713e134293fb319705030260dd037be1232d5104732884dea600b4018d5dd18659ec5352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
